baseURL = "https://timothywarrington.com/"
languageCode = "en-us"
title = "Timothy Warrington"
disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]
